apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  annotations:
    krateo.io/icon: fa-box
  name: swift
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/swift
    version: "0.2.0"
