apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: openstack-rabbitmq
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/openstack-rabbitmq
    version: "0.1.0"
