apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  annotations:
    krateo.io/icon: fa-chart-line
  name: gnocchi
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/gnocchi
    version: "0.2.0"
