apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  annotations:
    krateo.io/icon: fa-server
  name: libvirt
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/libvirt
    version: "0.2.0"
