apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: openstack-libvirt
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/openstack-libvirt
    version: "0.1.0"
