apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  annotations:
    krateo.io/icon: fa-table-columns
  name: horizon
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/horizon
    version: "0.2.0"
