apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  annotations:
    krateo.io/icon: fa-money-bill
  name: cloudkitty
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/cloudkitty
    version: "0.2.0"
