apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: watcher
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/watcher
    version: "0.1.1"
