apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  name: neutron
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/neutron
    version: "0.1.0"
