apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  annotations:
    krateo.io/icon: fa-thumbtack
  name: placement
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/placement
    version: "0.2.0"
