apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  annotations:
    krateo.io/icon: fa-gauge-high
  name: skyline
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/skyline
    version: "0.2.0"
