apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  annotations:
    krateo.io/icon: fa-lock
  name: barbican
  namespace: openstack-system
spec:
  chart:
    url: oci://ghcr.io/braghettos/charts/barbican
    version: "0.2.0"
